# setup-firebase.ps1
# Interactive helper to create `firebase-config.js` from prompts.
# Run in PowerShell from the project root:
#   .\setup-firebase.ps1
# This writes `firebase-config.js` (do not commit to public repos).

function Read-Input([string]$prompt){
    Write-Host -NoNewline "$prompt: " -ForegroundColor Cyan
    return Read-Host
}

Write-Host "Firebase Config Setup" -ForegroundColor Green
$apiKey = Read-Input "apiKey"
$authDomain = Read-Input "authDomain (e.g. project.firebaseapp.com)"
$projectId = Read-Input "projectId"
$storageBucket = Read-Input "storageBucket (e.g. project.appspot.com)"
$messagingSenderId = Read-Input "messagingSenderId"
$appId = Read-Input "appId"

$config = "// Generated by setup-firebase.ps1 - do NOT commit this file to public repos`n"
$config += "window.FIREBASE_CONFIG = {`n"
$config += "  apiKey: \"$apiKey\",`n"
$config += "  authDomain: \"$authDomain\",`n"
$config += "  projectId: \"$projectId\",`n"
$config += "  storageBucket: \"$storageBucket\",`n"
$config += "  messagingSenderId: \"$messagingSenderId\",`n"
$config += "  appId: \"$appId\"`n"
$config += "};`n"

$outFile = Join-Path -Path (Get-Location) -ChildPath 'firebase-config.js'
Set-Content -Path $outFile -Value $config -Encoding UTF8
Write-Host "Created $outFile" -ForegroundColor Green
Write-Host "Reminder: include <script src=\"firebase-config.js\"></script> in index.html before firebase.js" -ForegroundColor Yellow
